

on:
  push:
    branches:
      - master


jobs:
    deploy_prod:
      runs-on: ubuntu-latest
      environment: production

      steps:
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.AZURE_DEPLOY }}
            known_hosts: 'adding known hosts'
        

        - name: Add Known Host
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
        - name: Deploy Frontend with SSH
          run: rsync -navz client ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}

        - name: Deploy Backend with SSH
          run: rsync -azvn backend ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}

      